Vagrant.configure("2") do |config|

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "generic/rhel8"
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "192.168.40.10"

    vm1.vm.provider "vmware" do |vb|
      vb.gui = true
      vb.memory = "1024"
    end
  end

#   # Добавление второй виртуалки
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "generic/rhel8"
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "192.168.50.10"

    vm2.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "1024"
    end
  end
end
